### ISSUE TITLE
Invalid format

### ISSUE THREAD

**Issue by fractalawareness** [barbibulle/hippo#3]
Hello!
I'm using ffmpeg + mp4dash to convert mp4 (https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_h264.mov) to desired format like this:
```
ffmpeg -y -threads 4 -thread_queue_size 512 -i ./big_buck_bunny_720p_h264.mov -pix_fmt yuv420p -movflags frag_keyframe+faststart -c:v libx264 -preset veryslow -crf 25 -f mp4 -an -r 30 -t 10 -write_tmcd 0 -x264opts 'keyint=30:min-keyint=30:vbv-maxrate=4800:vbv-bufsize=9600:scenecut=0:no-scenecut' ./results/ffmpegOutDefault.mp4

mp4dash -v -o ./results/dash1 --hippo ./results/ffmpegOutDefault.mp4
```
and then these files are generated `ffmpegOutDefault.mp4,  init-video-avc1.mp4,  stream.mpd, stream.msm`. But when dash.js tries to get some fragments of the video the server gives this error:
```
Error: invalid format
    at /home/appuser/app/lib/mp4.js:59:29
    at FSReqWrap.wrapper [as oncomplete] (fs.js:460:17)
```

Any ideas what could be wrong here?

**Comment by fractalawareness** [comment]
Solved by using **ffmpeg**->**mp4fragment**->**mp4dash**.
